name: Check Python scripts
on: [push]
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install expect
        run: sudo apt-get update && sudo apt-get install expect -y
      - name: Run script with expect
        run: |
          expect -c "
            spawn python your_script.py
            expect \"Choose an option: \"
            send \"1\r\"
            expect \"Enter student name: \"
            send \"John\r\"
            expect \"Enter subject: \"
            send \"Math\r\"
            expect \"Enter choice (1-5): \"
            send \"3\r\"
            interact
          "
